### ISSUE TITLE
Ellipsized namespace names on large clusters

### ISSUE THREAD

**Issue by elizabeth-dev** [ameerthehacker/kubelive#13]
**Describe the bug**
When trying to visualize pods in a cluster with a large number of namespaces (36 namespaces in thi s case), there's not enough space in one line to show all the namespace names, and only the numbers are shown (some of them get ellipsized too). This makes selecting a namespace practically not possible.

Probably this will happen with smaller screens, or with long-named namespaces too.

**To Reproduce**

1. Create a k8s cluster with a large number of namespaces (no pods are needed)
2. Exec `kubelive get pod`
3. The namespaces tags are barely visible, if visible at all.

**Expected behavior**
My suggestion is to allow the namespace list to extend to more than one line if needed. A more complex option is to implement some kind of "scrolling" (like `top`, or `journalctl`).

**Screenshots**
Unfortunately, i'd prefer not to attach any screenshot, as i'm not authorized to share any information about the clusters i work with. I'll try to create an empty temporal cluster with fake namespaces.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: Chrome 79 (???)
- Version: v.1.2.1

**Comment by ameerthehacker** [comment]
Thanks @elizabeth-dev for reporting the issue, this is a known bug and I'm working on a workaround and will release it soon!

**Comment by nikhilgorantla** [comment]
@ameerthehacker  Any Time on Bug Fix ?

**Comment by ameerthehacker** [comment]
@nikhilgorantla this is an upstream issue from one of the library I use, so can't promise on a timeline but I'm actively exploring on rebuilding that library to support scrolling
