### ISSUE TITLE
Feature: Don't use `d` for delete

### ISSUE THREAD

**Issue by ghostsquad** [ameerthehacker/kubelive#15]
**Is your feature request related to a problem? Please describe.**

A similar CLI had a similar problem, in that they creators chose `d` as a shortcut to delete. However, the side effect was that it became _too_ easy to accidentally delete something.

https://github.com/derailed/k9s/issues/61

**Describe the solution you'd like**

Allow customized key bindings? Turn "deletion" hotkey off by default, with a configuration option to allow it, while showing the user how to bind a key to it.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ameerthehacker** [comment]
Hey @ghostsquad, thanks for pointing it out, even though D key is used for deletion an Y/N prompt is shown to the user before the resource is actually deleted which should avoid accidental deletion yet customizable key binding does sound a good to have feature

**Comment by ghostsquad** [comment]
ah, neat. Very smart.

**Comment by ameerthehacker** [comment]
closing this issue, please feel free to reopen it if you need to
