### ISSUE TITLE
Support short names of resources

### ISSUE THREAD

**Issue by sadedil** [ameerthehacker/kubelive#25]
**Is your feature request related to a problem? Please describe.**
While I'm using the `kubectl`, always use short names of resources like `kubectl get svc` or `kubectl get po`. Currently `kubelive` not supports this shortcuts.

**Describe the solution you'd like**
I think it will be very useful `kubelive` supports them. Currently `kubelive get svc` says`resource svc is not supported` and I think it should be equal with `kubelive get services`

**Describe alternatives you've considered**
N/A

**Additional context**
You can get all shortcuts supported by the `kubectl` with just typing `kubectl api-resources`

Thanks

**Comment by ameerthehacker** [comment]
@sadedil thanks for the suggestion,  will schedule this feature for the next releass

**Comment by ameerthehacker** [comment]
@sadedil this has been published to npm in version 1.5.0, do check and let me know.
