### ISSUE TITLE
Support the `--context` flag on `get` 

### ISSUE THREAD

**Issue by stevenctl** [ameerthehacker/kubelive#29]
I am usually trying to manage multiple clusters at once.

**Describe the solution you'd like**

It would be nice to leave my configured context/cluster (`kubectl config set-context`) alone and just inline `kubelive get pods --context=$CLUSTER0_CTX`, similar to `kubectl`

**Comment by ameerthehacker** [comment]
This is a valid usecase, will schedule this for next release

**Comment by ameerthehacker** [comment]
@stevenctl this has been released to npm in version 1.4.0, do check and let me know!
